### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by justinpenner** [justinpenner/TalkingLeaves#14]
- [ ] Map Hyperglot charsets to Glyphs glyph names instead of checking everything by codepoints, to fix #13 
- [ ] Implement context menu re: #6 
- [ ] Automate dependency installs as outlined in [#2](https://github.com/justinpenner/TalkingLeaves/issues/2#issuecomment-2071163248)
- [ ] Add to Plugin Manager
